version: "3"

services:
  node:
    build: .
    env_file: admin_front/admin.env
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd admin_front && PORT=8000 yarn start'
    ports:
      - "8000:8000"
